### ISSUE TITLE
Press the space bar to start cooking OR start directly with three onions on the pot

### ISSUE THREAD

**Issue by AlexWanghaoming** [HumanCompatibleAI/overcooked_ai#101]
Dear developer,
Which line of overcooked Env to alter the config that press the space bar to start cooking OR start directly with three onions on the pot?
Thanks

**Comment by jyan1999** [comment]
Hi Alex,

`Which line of overcooked Env to alter the config that press the space bar to start cooking `
The **INTERACT** action to cook soup is executed [here](https://github.com/HumanCompatibleAI/overcooked_ai/blob/29524d104051e864e4f24a9012bd1c875fa7d107/src/overcooked_ai_py/mdp/overcooked_mdp.py#L1508-L1512). 

`start directly with three onions on the pot`
Currently this can't be done as the game requires an INTERACT action to start cooking the soup. This is a newer feature, and you can use [an older release](https://github.com/HumanCompatibleAI/overcooked_ai/tree/6eaceb0a9a2501f1b9fccbf4c7016d6662ed1108) if this behavior is undesirable. A temporary hotfix is to move the block of code that starts cooking to [step_environment_effects](https://github.com/HumanCompatibleAI/overcooked_ai/blob/29524d104051e864e4f24a9012bd1c875fa7d107/src/overcooked_ai_py/mdp/overcooked_mdp.py#L1683-L1687), so all the cooking will start automatically.

We are also in the process of adding support for this feature and it will be available ASAP.

**Comment by AlexWanghaoming** [comment]
Hi jyan1999, 
Thanks for your quick feedback and revision.
