### ISSUE TITLE
Cannot import env containing tomato task, order and ingredients

### ISSUE THREAD

**Issue by KhoiDOO** [HumanCompatibleAI/overcooked_ai#106]
Dear authors,

I'm trying to create an AgentEvaluator generated from the layout "asymmetric_advantages_tomato" however I get trouble in the problem shown below:

![image](https://user-images.githubusercontent.com/92308124/210724203-8bd40cda-69a2-46e9-9395-5678cbb58f9c.png)

Could you pls show me if I have missed something, or how do I resolve this 

Sincere!

**Comment by micahcarroll** [comment]
`evaluate_human_model_pair` uses planning-based (not learned) human models, but the planning code was not designed to be able to deal with anything other than 3-onion soups. Changing the planning code would be very challenging and we're not planning on doing so.

I'd recommend either using learned human models for this layout, or attempting to change the planning code (not recommended).
