### ISSUE TITLE
Is It Possible to Configure the Environment for Single Agent?

### ISSUE THREAD

**Issue by mhz2180572509** [HumanCompatibleAI/overcooked_ai#108]
Hi, thanks for all of the great work and the nice environment! May I ask if it is possible to configure the environment to have only one single agent to work? Maybe in this case, the task can be easily developed as one single-agent RL task. Thank you in advance!

**Comment by jyan1999** [comment]
Hi,

Have you checked out this [issue](https://github.com/HumanCompatibleAI/overcooked_ai/issues/59)? I think currently the best way to accomplish this is still to substitute one agent with a [StayAgent](https://github.com/HumanCompatibleAI/overcooked_ai/blob/7a5dee45782489bbc7649a521a2e4125d27de40a/src/overcooked_ai_py/agents/agent.py#L265) and put it in an insignificant spot on the layout. It is quite easy if you just want to evaluate with a StayAgent, though if you want to train with one using the existing framework you might need to define[ another policy class ](https://docs.ray.io/en/latest/rllib/rllib-concepts.html). It can be a static class so it won't be too complicated to implement. 

Let me know if this helps!

**Comment by mhz2180572509** [comment]
Thank you for your reply, to set one stay-agent should work very well, thank you very much!
