### ISSUE TITLE
Speed up game creation demo

### ISSUE THREAD

**Issue by micahcarroll** [HumanCompatibleAI/overcooked_ai#112]
Unclear why creating a game takes so long, maybe there is an easy speedup somewhere?

**Comment by jyan1999** [comment]
Found a couple of places to improve that could help with the performance and amended the demo_merge pr. From testing locally creating a two-agent game now takes about 12 secs, which is about 6 seconds faster than before. I'll see what else can be done, though from the looks of it most of the time is spent creating a Ray instance, which is outside of our control.
