### ISSUE TITLE
How can I visualize agents' trajectory just given a sequence of actions

### ISSUE THREAD

**Issue by wudiymy** [HumanCompatibleAI/overcooked_ai#118]
Hello, authors. The agents' initial positions seem to be fixed. If given a fixed action sequence, the trajectory should be fixed. I want to know how to visualize the trajectory if I have the action sequences of two agents? Thanks.

**Comment by jyan1999** [comment]
Hi,

Have you checked out [this Colab notebook](https://colab.research.google.com/drive/1AAVP2P-QQhbx6WTOnIG54NXLXFbO7y6n#scrollTo=Z1RBlqADnTDw)? It shows an example of how you can see the agents in action given a sequence of joined actions.

**Comment by wudiymy** [comment]
Thanks for your advice. I solved it.
