### ISSUE TITLE
Feature request: Gymnasium & PettingZoo support

### ISSUE THREAD

**Issue by elliottower** [HumanCompatibleAI/overcooked_ai#120]
Hi,  would it be possible to add [PettingZoo](https://github.com/Farama-Foundation/PettingZoo) support in the future? The current setup.py also uses OpenAI gym, which has not been maintained for a few years now, [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of it. 

Gymnasium and PettingZoo are compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib), [tianshou](https://github.com/thu-ml/tianshou) and [CleanRL](https://github.com/vwxyzjn/cleanrl) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon) as well as other tools such as Comet and WandB.

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues. 

Adding PettingZoo support would be a bit more complicated, but if needed I would be happy to help look over code or answer any questions. It would be really helpful for future researchers, and we would be excited to list it in the third party environments lists ([PettingZoo](https://pettingzoo.farama.org/environments/third_party_envs/), [Gymnasium](https://gymnasium.farama.org/environments/third_party_environments/)).

**Comment by micahcarroll** [comment]
Hi @elliottower, does [this](https://github.com/HumanCompatibleAI/overcooked_ai/pull/123/files#diff-8f1a35244d81486e07eecac44167715a54afa3c2daf194a362a478b22a83bb24) look sufficient to you / what you had in mind?

**Comment by elliottower** [comment]
> Hi @elliottower, does [this](https://github.com/HumanCompatibleAI/overcooked_ai/pull/123/files#diff-8f1a35244d81486e07eecac44167715a54afa3c2daf194a362a478b22a83bb24) look sufficient to you / what you had in mind?

Left some comments on that PR but just looked it over again and posting here as well, looks good to me.
