### ISSUE TITLE
How to repeat the Near-optimal model-based planner and Planning experiments(in old dynamics))？

### ISSUE THREAD

**Issue by wittycheng** [HumanCompatibleAI/overcooked_ai#124]
I am wondering how to use the deprecated MediumLevelPlanner to repeat. I met this problem
<img width="557" alt="image" src="https://github.com/HumanCompatibleAI/overcooked_ai/assets/106607865/0df0428c-b683-47f0-90ab-621349770861">
<img width="463" alt="image" src="https://github.com/HumanCompatibleAI/overcooked_ai/assets/106607865/a029249b-7505-4169-81c3-395264b67631">

**Comment by jyan1999** [comment]
Hi,

If you have specific needs for this function, I'd recommend going back and using an older commit before this method was deprecated and following the instructions included in that commit. For example the [DELIVERY_REW_THRES](https://github.com/HumanCompatibleAI/overcooked_ai/blob/62a0f2bf7efc280c5ed87c08ea58bdfc02188b90/src/overcooked_ai_py/planning/planners.py#L23) can be found in this commit. Note we are unlikely to be able to offer support for deprecated methods and classes.

**Comment by wittycheng** [comment]
thank you， I will take a try

**Comment by micahcarroll** [comment]
Just to add on to that, if you want to reproduce the old experiments exactly as in the paper I'd use [this tagged version](https://github.com/HumanCompatibleAI/overcooked_ai/releases/tag/neurips2019)
