### ISSUE TITLE
PettingZoo

### ISSUE THREAD

**Issue by nil123532** [HumanCompatibleAI/overcooked_ai#127]
Does the author use PettingZoo Library to implement OverCooked Environment?

**Comment by micahcarroll** [comment]
What do you mean? We don't use PettingZoo, but if I remember correctly PettingZoo tried to incorporate Overcooked in it at some point.

**Comment by micahcarroll** [comment]
What do you mean? We don't use PettingZoo, but if I remember correctly PettingZoo tried to incorporate Overcooked in it at some point.

**Comment by nil123532** [comment]
If you go on [overcooked_ai](https://github.com/HumanCompatibleAI/overcooked_ai/tree/master)/[src](https://github.com/HumanCompatibleAI/overcooked_ai/tree/master/src)/[overcooked_ai_py](https://github.com/HumanCompatibleAI/overcooked_ai/tree/master/src/overcooked_ai_py)/[mdp](https://github.com/HumanCompatibleAI/overcooked_ai/tree/master/src/overcooked_ai_py/mdp)
on line 672 - from pettingzoo.utils.env import ParallelEnv 

Why do you import that?

**Comment by jyan1999** [comment]
The environment was created due to a feature request for PettingZoo support (details can be found in this [issue](https://github.com/HumanCompatibleAI/overcooked_ai/issues/120)). This environment is not used anywhere in the codebase and exists merely as an optional supplement.

**Comment by micahcarroll** [comment]
Ah, right! Thanks @jyan1999!

**Comment by nil123532** [comment]
Thank you!
