### ISSUE TITLE
 Some problems during installation

### ISSUE THREAD

**Issue by IMGDemon** [HumanCompatibleAI/overcooked_ai#140]
Dear author,when I run the following script "./run_tests.sh" from the src/human_aware_rl directory, there is an errors I don't understand what happenning and don't how to solve it. The error is as follows:
FileNotFoundError: [Errno 2] No such file or directory: '/home/file2/ray_results/PPO_cramped_room_False_nw=16_vf=0.000100_es=0.200000_en=0.000500_kl=0.200000_11_2024-04-12_14-13-38v6uj1upa'

There are the information of the directory I used:(overcooked_ai) file2@hciubuntu:~/overcooked_ai/src/human_aware_rl$

**Comment by micahcarroll** [comment]
I'm not able to reproduce the error. I would try to run the individual commands in `./run_tests.sh` to try to isolate the issue further. Feel free to share a stack trace here
