### ISSUE TITLE
Value Error - Overcooked_ai 1.1.0

### ISSUE THREAD

**Issue by dkaul09** [HumanCompatibleAI/overcooked_ai#142]
Hi, I am currenly using the overcooked_ai 1.1.0 version and when I am running the testing suite, I am getting a value error from the test_mdp_serialization . I have not changed any lines of code besides changing np.int to int as np.int is deprecated. 
<img width="1330" alt="Screenshot 2024-05-11 at 3 34 04 PM" src="https://github.com/HumanCompatibleAI/overcooked_ai/assets/111927365/95f8bc28-075b-48e8-89cb-844d290e2247">

**Comment by micahcarroll** [comment]
The test passes on the Github Actions, suggesting that maybe there is a discrepancy with your local setup. That being said, if you manage to figure out the fix and it's something in the code, feel free to make a PR!
