### ISSUE TITLE
New Training and Evaluating Platform

### ISSUE THREAD

**Issue by xihuai18** [HumanCompatibleAI/overcooked_ai#144]
We implement a training and evaluating platform using Overcooked-ai, https://github.com/sjtu-marl/ZSC-Eval. 
ZSC-Eval includes 7 strong algorithms and novel evaluation partners, and a human experiment platform.
Would it be added to the "Research Papers using Overcooked AI" section for reference?

**Comment by micahcarroll** [comment]
Yes, absolutely, if you make a PR I will merge it!
