### ISSUE TITLE
Replace instances of np.Inf to np.inf following Numpy 2.0 release

### ISSUE THREAD

**Issue by luke9kim8** [HumanCompatibleAI/overcooked_ai#149]
Since Numpy 2.0 release in June 2024, `np.Inf` is deprecated (See 'Highlights' in the [release note](https://github.com/numpy/numpy/releases/tag/v2.0.0)). Would it be possible to have instances of `np.Inf` replaced with `np.inf` so we can use Numpy 2.0 when using this envrionment?

Creating the issue directly because I don't think there is a formal contribution guide. Please feel free to close this and link one in the comments if there is one.

**Comment by micahcarroll** [comment]
Thank you for pointing this our @luke9kim8!

Is np.inf compatible with older versions of Numpy? If so, feel free to find and replace all the instances, and make a PR!
