### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by micahcarroll** [HumanCompatibleAI/overcooked_ai#23]
Make all path directory code OS agnostic. Would require using `os.path.join` rather than manually adding slashes between directory names in many places.

**Comment by mesutyang97** [comment]
Hi Micah, I have looked into this on the side, and unfortunately ray 0.8.5 does not support windows

**Comment by micahcarroll** [comment]
Ah, ok, sounds good – I guess this is simply not going to happen then.
