### ISSUE TITLE
Add additional ingredients

### ISSUE THREAD

**Issue by nathan-miller23** [HumanCompatibleAI/overcooked_ai#43]
Adapting the `Recipe` class to handle additional ingredients for a more diverse soup space. Might involve changes to the `OvercookedGridworld` and `OvercookedEnv` classes to handle the new ingredients

**Comment by micahcarroll** [comment]
Just as a comment – this seems to me like less important than other issues in the to-do list. Adding ingredients will increase the amount of code we have to maintain and test, and we currently have no plans for actually using such code. Instead, visualizations infrastructure improvements would be useful to everyone pretty much immediately, and as such would be very worthwhile to maintain.
