### ISSUE TITLE
Native Python Visualization

### ISSUE THREAD

**Issue by nathan-miller23** [HumanCompatibleAI/overcooked_ai#45]
Updating the existing JS graphics to provide native python support for overcooked GUI.

**Comment by bmielnicki** [comment]
Result of this task would be a way of displaying OvercookedState to produce view like [this](https://raw.githubusercontent.com/HumanCompatibleAI/overcooked_ai/master/images/screenshot.png)

**Comment by bmielnicki** [comment]
Pygame offers enough features to make visualization of the state (and playing game with AI) work. The only thing it is missing from the ideal solution is integration with Ipython notebook (seems like displaying pygame inside jupyter cell is problematic). Do we care about that a bit, much or not at all?

Possible workarounds include:
- use skulpt, there is [project](https://github.com/Petlja/pygame4skulpt) that has not everything implemented but probably enough
- implement state visualization as js code and open js in web browser/inside jupyter cell (as currently is done with charts https://github.com/HumanCompatibleAI/overcooked_ai/pull/38 )

**Comment by nathan-miller23** [comment]
the only reason we would ever want to use the graphics in a jupyter notebooked would be for static state visualization, not game play. For example, it would be super cool to be able to provide an `OvercookedState` instance, `state` to a function call like `visualize_state(state)` and have it display a JPG like the one you linked above inside a notebook.

There is no use case for playing interactive games inside a notebook

With that in mind, I'll leave it to you to choose the best tool (I'm not particularly familiar with pygame or skulpt) with the only constraint that all visualization (static and interactive) must be able to be invoked from a python main function

**Comment by micahcarroll** [comment]
By the way, you can still have sliders with ipythonwidgets that enable you to flick between images of the same trajectory – that comes in handy. But we definitely will not have to _play_ with agents through the notebook – in fact, we want the gameplay dynamics to have only one ground truth - overcooked-demo, or things will get kind of confusing (it would be hard and unnecessary work to perfectly match up the smoothness and gameplay experience of overcook-demo in another game environment).

And yes, I agree with Nathan that the main objective here is to have a function `visualize_state` that goes from OvercookedState to JPG.

**Comment by bmielnicki** [comment]
Thanks for the information.

Alternative approach would be to use overcooked-demo code and put into ipython cell, but it is probably more time consuming and creates additional dependency between python and js code.

I will create task for this and put in to-do list.
