### ISSUE TITLE
Create Trajectory class

### ISSUE THREAD

**Issue by bmielnicki** [HumanCompatibleAI/overcooked_ai#52]
Creating a Trajectory class to better abstract away a lot of the complex dictionary parsing in a more Object Oriented fashion.
Moved from https://github.com/HumanCompatibleAI/overcooked_ai/issues/44 as this issue will probably wait a bit.

**Comment by bmielnicki** [comment]
I have a couple of questions before starting making code here:

1. Do we want this task done considering it was initially part of https://github.com/HumanCompatibleAI/overcooked_ai/issues/44 that probably won't happen (current discussion ended on the decision to not do this issue)? 

2. How much do we care about fully backward compatibility here? How I can solve backward compatibility:
a) Implement a method that returns trajectory dict in its current form
b) Implement magic methods like `__getitem__` to let users use trajectory object exactly like trajectory dict. It is a bit constraining (at least prevent from use magic method in the way different that was implemented in dict) and there is a risk of forgetting some magic method.
c) just don't care about it - edit overcooked-ai and harl repo to work with the changes and that it enough
d) some mix of above

3. Should I create it from the master branch or trajectory visualization PR code https://github.com/HumanCompatibleAI/overcooked_ai/pull/38 (it depends if anyone wants this change before the merge of https://github.com/HumanCompatibleAI/overcooked_ai/pull/38 will happen - currently it waits for review after some refactor and added compatibility with the adjectives)?

**Comment by micahcarroll** [comment]
@nathan-miller23 & @mesutyang97, I think this is kind of up to you – I wouldn't expect either of you to be using this version of the code anytime soon (unless you think it valuable enough to spend time merging it with yours). Moreover, I expect this to require quite a large overhaul of human_aware_rl and other repos, such as your own project ones – so even reviewing this PR and the corresponding ones in other repos (or making those yourselves) would likely be a lot of work.

I personally think that it's probably not worth it right now, and we should punt it to a better time in which there is less pressure on getting actual research done.
