### ISSUE TITLE
Have only one single player?

### ISSUE THREAD

**Issue by leobxpan** [HumanCompatibleAI/overcooked_ai#59]
Thanks for the great work. Is it possible to configure the environment to have just one player instead of multiple? So the collaboration component will be removed and it becomes a standard RL task.

**Comment by micahcarroll** [comment]
Yes, I believe the environment side should handle this fine. However, it might require some changes to the DRL framework, which I expect would be quite easy to make. 

If you want to test the one-player setting in a preliminary manner right now without making any changes, I would encourage using a StayAgent as the second agent, and placing them in a location of the layout that is not important for the completion of the task – this should effectively be equivalent to training a single agent (but would require placing the StayAgent in the same position at test time too).

**Comment by leobxpan** [comment]
Gotcha. Thank you!
