### ISSUE TITLE
Agent reset during activation overrides agent's index and mdp

### ISSUE THREAD

**Issue by MarinLGU** [HumanCompatibleAI/overcooked_ai#77]
Hello Micah and Nathan, 
I found out that my unability to run a GreedyHumanModel agent in overcooked demo comes from the agent being resetted during game's activation in overcooked demo [game.py](https://github.com/HumanCompatibleAI/overcooked-demo/blob/a9c68a93f705939bed41c3eec50333658e919d47/server/game.py#L547). I don't know how to handle that without breaking everything, though for now commenting out the "super" [here ](https://github.com/HumanCompatibleAI/overcooked_ai/blob/48d05dbbdb702d34c6769f31182ca619a3338ca0/src/overcooked_ai_py/agents/agent.py#L274) makes the agent run. Thanks for your help !

**Comment by micahcarroll** [comment]
Closing this as stale
