### ISSUE TITLE
Different versions?

### ISSUE THREAD

**Issue by pgerken** [HumanCompatibleAI/overcooked_ai#79]
I ran the overcooked demo via this link: https://humancompatibleai.github.io/overcooked-demo/
I also made a clone of https://github.com/HumanCompatibleAI/overcooked_ai and was able to get the demo running locally.

However, the remote demo can save game trajectories, but the local version doesn't have this option.
The remote version also "auto" cooks the soup instead of needing to press the space bar.

Is the code for the remote version available?

Thanks!

**Comment by micahcarroll** [comment]
Hi @pgerken,

Thanks for reaching out! The demo code used to have the trajectory-saving option before the repo was drastically refactored.

The code for the demo version [at this link](https://humancompatibleai.github.io/overcooked-demo/) is from [the github pages branch](https://github.com/HumanCompatibleAI/overcooked-demo/tree/gh-pages) of the repo.

Hope this answers your question! If you find a way to port the trajectory saving functionality to the new version of the repo, feel welcome to submit a PR request!

**Comment by bmielnicki** [comment]
Saving trajectory functionality pull request is here https://github.com/HumanCompatibleAI/overcooked-demo/pull/30. I'm not sure about compatibility with current master (it may be somehow dependent on my forked version of the overcooked_ai repo) as I wrote it long time ago.

**Comment by pgerken** [comment]
@bmielnicki 

> Saving trajectory functionality pull request is here [HumanCompatibleAI/overcooked-demo#29](https://github.com/HumanCompatibleAI/overcooked-demo/pull/29). I'm not sure about compatibility with current master (it may be somehow dependent on my forked version of the overcooked_ai repo but it is probably compatible with master) as I wrote it long time ago.

I tried to clone your repo: https://github.com/HumanCompatibleAI/overcooked-demo/pull/29 

However, when running...

   ./up.sh --env production

...it's failing on this in the service/Dockerfile

   RUN cp /overcooked_ai/src/overcooked_ai_py/visualization/web/* ./static/overcooked_visualizations_web

And.. if I comment that out, it fails when the docker image starts with the following....

   app_1  | Traceback (most recent call last):
   app_1  |   File "app.py", line 17, in <module>
   app_1  |     from overcooked_ai_py.visualization.extract_events import extract_events
   app_1  | ModuleNotFoundError: No module named 'overcooked_ai_py.visualization.extract_events'
   overcooked-demo_app_1 exited with code 1

My guess is that overcooked_ai_py.visualization.extract_events is not part of the overcooked_ai?

Maybe I need a different branch of overcooked_ai?

**Comment by pgerken** [comment]
Getting closer...

I changed the following in the server/Dockefile...

+#RUN git clone $OVERCOOKED_URL --branch $OVERCOOKED_BRANCH --single-branch /overcooked_ai
+RUN git clone https://github.com/bmielnicki/overcooked_ai --single-branch /overcooked_ai

and 

+#RUN git clone $HARL_URL --branch $HARL_BRANCH --single-branch /human_aware_rl
+RUN git clone https://github.com/bmielnicki/human_aware_rl --single-branch /human_aware_rl

This appears to give me the checkbox for saving trajectories, but still doesn't save it.

Also, the AI players are different.. I see RandAI and StayAI instead of Human-aware PPO Agent.  Is there a different repo with the better AI players like the ones found in https://humancompatibleai.github.io/overcooked-demo/?

**Comment by micahcarroll** [comment]
> Also, the AI players are different.. I see RandAI and StayAI instead of Human-aware PPO Agent. Is there a different repo with the better AI players like the ones found in https://humancompatibleai.github.io/overcooked-demo/?

The dynamics of the environment are different between the old and new version of overcooked-demo (the soup cooking doesn't require an extra interact action), and I don't believe PPO agents for the new version were ever trained and set aside for the purposes of the demo.
