### ISSUE TITLE
Invalid Value (NaNs) in Overcooked Class 

### ISSUE THREAD

**Issue by aenneas** [HumanCompatibleAI/overcooked_ai#85]
https://github.com/HumanCompatibleAI/overcooked_ai/blob/bdbf0232adde1412db87975d0ec2357093775ef4/src/overcooked_ai_py/mdp/overcooked_env.py#L549

This line was added to fix the "soup_cooking_time" issue. But now it returns:
"RuntimeWarning: invalid value encountered in multiply
  gym.spaces.Box(high * 0, high, dtype=np.float32)".
  
 Simple printing shows that variable _high_ is an array of Infs, and thus high * 0 becomes an array of NaNs.

**Comment by micahcarroll** [comment]
As a temporary solution, I've [changed the value to a large number](https://github.com/HumanCompatibleAI/overcooked_ai/commit/9395f2d4dea856d830c9a337bf629dffc5e93377). We'll figure a better solution for this soon.

**Comment by aenneas** [comment]
> Thanks for reaching out!
> 
> As a temporary solution, I've [changed the value to a large number](https://github.com/HumanCompatibleAI/overcooked_ai/commit/9395f2d4dea856d830c9a337bf629dffc5e93377). We'll figure a better solution for this soon.

It actually has a simpler solution than I thought. The issue is due to the next line actually:
`return gym.spaces.Box(high * 0, high, dtype=np.float32)`

The 0*high is the problem. This solves it:
high = np.ones(obs_shape) * float("inf")
low = np.zeros(obs_shape)
return gym.spaces.Box(low, high, dtype=np.float32)

**Comment by micahcarroll** [comment]
Ah, I see – thanks so much!
