### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by MahzadK** [HumanCompatibleAI/overcooked_ai#88]
This link https://github.com/HumanCompatibleAI/human_aware_rl/blob/master/human_aware_rl/overcooked_interactive.py  is not exist.

**Comment by micahcarroll** [comment]
This is the file you're looking for: https://github.com/HumanCompatibleAI/human_aware_rl/blob/neurips2019/human_aware_rl/overcooked_interactive.py

Where did you find this link linked?

**Comment by MahzadK** [comment]
Here:
https://github.com/HumanCompatibleAI/overcooked_ai/blob/master/README.md#python-visualizations-
