### ISSUE TITLE
trajectory replay code

### ISSUE THREAD

**Issue by AnnieJohnson25** [HumanCompatibleAI/overcooked_ai#98]
Hi,
I have been trying to investigate how to get the individual frames for each time step from the trajectory. Therefore, I was looking for the code that replays the trajectory json file. 
That is the code that does this: https://humancompatibleai.github.io/overcooked-demo/replay
I am not able to understand how a 30s game play is equivalent to 204 steps, whereas a 60s game play is equivalent to 404 steps. 

It would be great if some guidance could be given regarding this.

Thank you!

**Comment by micahcarroll** [comment]
I think there might be some bug in the replay functionality – it had always been a bit finicky. If you find it, you're more than welcome to submit a PR. 

In general, for greatest reliability, I would try to process trajectories (and view them) in python as much as possible.
